// <auto-generated />
using Lab36Cameron.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab36Cameron.Migrations
{
    [DbContext(typeof(SongEntryDbContext))]
    [Migration("20171102190046_ListUpdated")]
    partial class ListUpdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab36Cameron.Models.Contributors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("Lab36Cameron.Models.SongItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Audio");

                    b.Property<int?>("ContributorsId");

                    b.Property<int>("FeatId");

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ContributorsId");

                    b.ToTable("SongItem");
                });

            modelBuilder.Entity("Lab36Cameron.Models.SongItem", b =>
                {
                    b.HasOne("Lab36Cameron.Models.Contributors")
                        .WithMany("PlayList")
                        .HasForeignKey("ContributorsId");
                });
#pragma warning restore 612, 618
        }
    }
}
